# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright 2013 OpenStack Foundation
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""uos floatingips

Revision ID: 1966c879d9ef
Revises: 469134760b91
Create Date: 2013-12-25 21:27:12.030851

"""

# revision identifiers, used by Alembic.
revision = '1966c879d9ef'
down_revision = '469134760b91'

# Change to ['*'] if this migration applies to all plugins

migration_for_plugins = [
    'neutron.plugins.ml2.plugin.Ml2Plugin'
]

from alembic import op
import sqlalchemy as sa

from neutron.db import migration


def upgrade(active_plugins=None, options=None):
    if not migration.should_run(active_plugins, migration_for_plugins):
        return

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floatingips',
                  sa.Column('uos_name', sa.String(length=255), nullable=True))
    op.add_column('floatingips',
                  sa.Column('floating_subnet_id',
                            sa.String(length=255), nullable=True))

    ### end Alembic commands ###


def downgrade(active_plugins=None, options=None):
    if not migration.should_run(active_plugins, migration_for_plugins):
        return

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floatingips', 'uos_name')
    op.drop_column('floatingips', 'floating_subnet_id')
    ### end Alembic commands ###
